#!/usr/bin/env bash
# Bash script that installs nginx on an ubuntu machine.
# The scripts also configures the default webpage served to be "Hello World!"
# When request url matches /redirect_me, it redirects to my github channel.

sudo apt-get update -y

sudo apt-get install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

line_replacement="server_name -;\n\trewrite ^\/redirect_me https:\/\/github.com\/donbless27 permanent;"

sudo sed -i "s/server_name -;/$line_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
