#!/usr/bin/env bash
# Configuring ubuntu new machine

#Installing and updating Nginx
sudo apt-get update
sudo apt-get install nginx -y

#Creating index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performing a redirection
line_replacement="server_name -;\n\trewrite ^\/redirect_me https:\/\/github.com\/donbless27 permanent;"
sudo sed -i "s/server_name -;/$line_replacement/" /etc/nginx/sites-enabled/default

# Creating an error page
line_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$line_replacement/" /etc/nginx/sites-enabled/default


# HTTP custom response header
sudo sed -i "/server_name -/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Testing Nginx 
sudo nginx -t

# Restarting Nginx
sudo service nginx restart 
