#!/usr/bin/env bash
# configures a new Ubuntu machine

# Install nginx on web-01 server
apt-get -y update
apt-get -y install nginx

# Create a firts index.html page
echo "Hello World!" > /var/www/html/index.html

# Add to the nginx configuration file a redirection to another page
line_replacement="server_name -;\n\trewrite ^\/redirect_me https:\/\/github.com\/donbless27 permanent;"
sudo sed -i "s/server_name -;/$line_replacement/" /etc/nginx/sites-enabled/default
fi

# Add to the nginx configuration file a error page 404
line_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$line_replacement/" /etc/nginx/sites-enabled/default

# Add custom response header to know the server name 
sudo sed -i "/server_name -/a add_header X-Served-By $HOSTNAME;" /etc/niginx/sites-enabled/default
fi

#Check for nginx error
sudo nginx -t

#Restart nginx
service nginx restart
